// Generated by gencpp from file common/FireDoorControlRequest.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_FIREDOORCONTROLREQUEST_H
#define COMMON_MESSAGE_FIREDOORCONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common
{
template <class ContainerAllocator>
struct FireDoorControlRequest_
{
  typedef FireDoorControlRequest_<ContainerAllocator> Type;

  FireDoorControlRequest_()
    : command(0)  {
    }
  FireDoorControlRequest_(const ContainerAllocator& _alloc)
    : command(0)  {
  (void)_alloc;
    }



   typedef int32_t _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::common::FireDoorControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::FireDoorControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FireDoorControlRequest_

typedef ::common::FireDoorControlRequest_<std::allocator<void> > FireDoorControlRequest;

typedef boost::shared_ptr< ::common::FireDoorControlRequest > FireDoorControlRequestPtr;
typedef boost::shared_ptr< ::common::FireDoorControlRequest const> FireDoorControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::FireDoorControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::FireDoorControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::FireDoorControlRequest_<ContainerAllocator1> & lhs, const ::common::FireDoorControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::FireDoorControlRequest_<ContainerAllocator1> & lhs, const ::common::FireDoorControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::FireDoorControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::FireDoorControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::FireDoorControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::FireDoorControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::FireDoorControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::FireDoorControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::FireDoorControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a54bc0c5f4abe9ad44d29292ec0800d";
  }

  static const char* value(const ::common::FireDoorControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a54bc0c5f4abe9aULL;
  static const uint64_t static_value2 = 0xd44d29292ec0800dULL;
};

template<class ContainerAllocator>
struct DataType< ::common::FireDoorControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/FireDoorControlRequest";
  }

  static const char* value(const ::common::FireDoorControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::FireDoorControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 command \n"
"# 0关闭 1开启\n"
;
  }

  static const char* value(const ::common::FireDoorControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::FireDoorControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FireDoorControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::FireDoorControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::FireDoorControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_FIREDOORCONTROLREQUEST_H
