// Generated by gencpp from file common/MappingRequest.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_MAPPINGREQUEST_H
#define COMMON_MESSAGE_MAPPINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common
{
template <class ContainerAllocator>
struct MappingRequest_
{
  typedef MappingRequest_<ContainerAllocator> Type;

  MappingRequest_()
    : mapping_cmd(0)  {
    }
  MappingRequest_(const ContainerAllocator& _alloc)
    : mapping_cmd(0)  {
  (void)_alloc;
    }



   typedef int32_t _mapping_cmd_type;
  _mapping_cmd_type mapping_cmd;





  typedef boost::shared_ptr< ::common::MappingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::MappingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MappingRequest_

typedef ::common::MappingRequest_<std::allocator<void> > MappingRequest;

typedef boost::shared_ptr< ::common::MappingRequest > MappingRequestPtr;
typedef boost::shared_ptr< ::common::MappingRequest const> MappingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::MappingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::MappingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::MappingRequest_<ContainerAllocator1> & lhs, const ::common::MappingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mapping_cmd == rhs.mapping_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::MappingRequest_<ContainerAllocator1> & lhs, const ::common::MappingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::MappingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::MappingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::MappingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::MappingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::MappingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::MappingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::MappingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f16dec9fb6474486fb831f92fedc0c8";
  }

  static const char* value(const ::common::MappingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f16dec9fb647448ULL;
  static const uint64_t static_value2 = 0x6fb831f92fedc0c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::common::MappingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/MappingRequest";
  }

  static const char* value(const ::common::MappingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::MappingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 mapping_cmd\n"
"#1开始\n"
;
  }

  static const char* value(const ::common::MappingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::MappingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapping_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MappingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::MappingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::MappingRequest_<ContainerAllocator>& v)
  {
    s << indent << "mapping_cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mapping_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_MAPPINGREQUEST_H
