// Generated by gencpp from file common/PanoramicVideoUrlRequest.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_PANORAMICVIDEOURLREQUEST_H
#define COMMON_MESSAGE_PANORAMICVIDEOURLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common
{
template <class ContainerAllocator>
struct PanoramicVideoUrlRequest_
{
  typedef PanoramicVideoUrlRequest_<ContainerAllocator> Type;

  PanoramicVideoUrlRequest_()
    : panoramic_video_url()  {
    }
  PanoramicVideoUrlRequest_(const ContainerAllocator& _alloc)
    : panoramic_video_url(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _panoramic_video_url_type;
  _panoramic_video_url_type panoramic_video_url;





  typedef boost::shared_ptr< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PanoramicVideoUrlRequest_

typedef ::common::PanoramicVideoUrlRequest_<std::allocator<void> > PanoramicVideoUrlRequest;

typedef boost::shared_ptr< ::common::PanoramicVideoUrlRequest > PanoramicVideoUrlRequestPtr;
typedef boost::shared_ptr< ::common::PanoramicVideoUrlRequest const> PanoramicVideoUrlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::PanoramicVideoUrlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::PanoramicVideoUrlRequest_<ContainerAllocator1> & lhs, const ::common::PanoramicVideoUrlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.panoramic_video_url == rhs.panoramic_video_url;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::PanoramicVideoUrlRequest_<ContainerAllocator1> & lhs, const ::common::PanoramicVideoUrlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba607c1e80b486a09f8e68edd373cea1";
  }

  static const char* value(const ::common::PanoramicVideoUrlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba607c1e80b486a0ULL;
  static const uint64_t static_value2 = 0x9f8e68edd373cea1ULL;
};

template<class ContainerAllocator>
struct DataType< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/PanoramicVideoUrlRequest";
  }

  static const char* value(const ::common::PanoramicVideoUrlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string panoramic_video_url\n"
;
  }

  static const char* value(const ::common::PanoramicVideoUrlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.panoramic_video_url);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PanoramicVideoUrlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::PanoramicVideoUrlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::PanoramicVideoUrlRequest_<ContainerAllocator>& v)
  {
    s << indent << "panoramic_video_url: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.panoramic_video_url);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_PANORAMICVIDEOURLREQUEST_H
