// Generated by gencpp from file common/PanoramicVideoUrl.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_PANORAMICVIDEOURL_H
#define COMMON_MESSAGE_PANORAMICVIDEOURL_H

#include <ros/service_traits.h>


#include <common/PanoramicVideoUrlRequest.h>
#include <common/PanoramicVideoUrlResponse.h>


namespace common
{

struct PanoramicVideoUrl
{

typedef PanoramicVideoUrlRequest Request;
typedef PanoramicVideoUrlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PanoramicVideoUrl
} // namespace common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common::PanoramicVideoUrl > {
  static const char* value()
  {
    return "ba607c1e80b486a09f8e68edd373cea1";
  }

  static const char* value(const ::common::PanoramicVideoUrl&) { return value(); }
};

template<>
struct DataType< ::common::PanoramicVideoUrl > {
  static const char* value()
  {
    return "common/PanoramicVideoUrl";
  }

  static const char* value(const ::common::PanoramicVideoUrl&) { return value(); }
};


// service_traits::MD5Sum< ::common::PanoramicVideoUrlRequest> should match
// service_traits::MD5Sum< ::common::PanoramicVideoUrl >
template<>
struct MD5Sum< ::common::PanoramicVideoUrlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common::PanoramicVideoUrl >::value();
  }
  static const char* value(const ::common::PanoramicVideoUrlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::PanoramicVideoUrlRequest> should match
// service_traits::DataType< ::common::PanoramicVideoUrl >
template<>
struct DataType< ::common::PanoramicVideoUrlRequest>
{
  static const char* value()
  {
    return DataType< ::common::PanoramicVideoUrl >::value();
  }
  static const char* value(const ::common::PanoramicVideoUrlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common::PanoramicVideoUrlResponse> should match
// service_traits::MD5Sum< ::common::PanoramicVideoUrl >
template<>
struct MD5Sum< ::common::PanoramicVideoUrlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common::PanoramicVideoUrl >::value();
  }
  static const char* value(const ::common::PanoramicVideoUrlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::PanoramicVideoUrlResponse> should match
// service_traits::DataType< ::common::PanoramicVideoUrl >
template<>
struct DataType< ::common::PanoramicVideoUrlResponse>
{
  static const char* value()
  {
    return DataType< ::common::PanoramicVideoUrl >::value();
  }
  static const char* value(const ::common::PanoramicVideoUrlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MESSAGE_PANORAMICVIDEOURL_H
