// Generated by gencpp from file common/PatrolControl.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_PATROLCONTROL_H
#define COMMON_MESSAGE_PATROLCONTROL_H

#include <ros/service_traits.h>


#include <common/PatrolControlRequest.h>
#include <common/PatrolControlResponse.h>


namespace common
{

struct PatrolControl
{

typedef PatrolControlRequest Request;
typedef PatrolControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PatrolControl
} // namespace common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common::PatrolControl > {
  static const char* value()
  {
    return "fabfef9b528c8f61881ef7f060cb0b13";
  }

  static const char* value(const ::common::PatrolControl&) { return value(); }
};

template<>
struct DataType< ::common::PatrolControl > {
  static const char* value()
  {
    return "common/PatrolControl";
  }

  static const char* value(const ::common::PatrolControl&) { return value(); }
};


// service_traits::MD5Sum< ::common::PatrolControlRequest> should match
// service_traits::MD5Sum< ::common::PatrolControl >
template<>
struct MD5Sum< ::common::PatrolControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common::PatrolControl >::value();
  }
  static const char* value(const ::common::PatrolControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::PatrolControlRequest> should match
// service_traits::DataType< ::common::PatrolControl >
template<>
struct DataType< ::common::PatrolControlRequest>
{
  static const char* value()
  {
    return DataType< ::common::PatrolControl >::value();
  }
  static const char* value(const ::common::PatrolControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common::PatrolControlResponse> should match
// service_traits::MD5Sum< ::common::PatrolControl >
template<>
struct MD5Sum< ::common::PatrolControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common::PatrolControl >::value();
  }
  static const char* value(const ::common::PatrolControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::PatrolControlResponse> should match
// service_traits::DataType< ::common::PatrolControl >
template<>
struct DataType< ::common::PatrolControlResponse>
{
  static const char* value()
  {
    return DataType< ::common::PatrolControl >::value();
  }
  static const char* value(const ::common::PatrolControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MESSAGE_PATROLCONTROL_H
