// Generated by gencpp from file common/PatrolPicture.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_PATROLPICTURE_H
#define COMMON_MESSAGE_PATROLPICTURE_H

#include <ros/service_traits.h>


#include <common/PatrolPictureRequest.h>
#include <common/PatrolPictureResponse.h>


namespace common
{

struct PatrolPicture
{

typedef PatrolPictureRequest Request;
typedef PatrolPictureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PatrolPicture
} // namespace common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common::PatrolPicture > {
  static const char* value()
  {
    return "4b0c8b5f306638a944f76a5bcfd0a606";
  }

  static const char* value(const ::common::PatrolPicture&) { return value(); }
};

template<>
struct DataType< ::common::PatrolPicture > {
  static const char* value()
  {
    return "common/PatrolPicture";
  }

  static const char* value(const ::common::PatrolPicture&) { return value(); }
};


// service_traits::MD5Sum< ::common::PatrolPictureRequest> should match
// service_traits::MD5Sum< ::common::PatrolPicture >
template<>
struct MD5Sum< ::common::PatrolPictureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common::PatrolPicture >::value();
  }
  static const char* value(const ::common::PatrolPictureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::PatrolPictureRequest> should match
// service_traits::DataType< ::common::PatrolPicture >
template<>
struct DataType< ::common::PatrolPictureRequest>
{
  static const char* value()
  {
    return DataType< ::common::PatrolPicture >::value();
  }
  static const char* value(const ::common::PatrolPictureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common::PatrolPictureResponse> should match
// service_traits::MD5Sum< ::common::PatrolPicture >
template<>
struct MD5Sum< ::common::PatrolPictureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common::PatrolPicture >::value();
  }
  static const char* value(const ::common::PatrolPictureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::PatrolPictureResponse> should match
// service_traits::DataType< ::common::PatrolPicture >
template<>
struct DataType< ::common::PatrolPictureResponse>
{
  static const char* value()
  {
    return DataType< ::common::PatrolPicture >::value();
  }
  static const char* value(const ::common::PatrolPictureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MESSAGE_PATROLPICTURE_H
