// Generated by gencpp from file common/PID.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_PID_H
#define COMMON_MESSAGE_PID_H

#include <ros/service_traits.h>


#include <common/PIDRequest.h>
#include <common/PIDResponse.h>


namespace common
{

struct PID
{

typedef PIDRequest Request;
typedef PIDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PID
} // namespace common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common::PID > {
  static const char* value()
  {
    return "a6078b1c1836292d943f376c320c591d";
  }

  static const char* value(const ::common::PID&) { return value(); }
};

template<>
struct DataType< ::common::PID > {
  static const char* value()
  {
    return "common/PID";
  }

  static const char* value(const ::common::PID&) { return value(); }
};


// service_traits::MD5Sum< ::common::PIDRequest> should match
// service_traits::MD5Sum< ::common::PID >
template<>
struct MD5Sum< ::common::PIDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common::PID >::value();
  }
  static const char* value(const ::common::PIDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::PIDRequest> should match
// service_traits::DataType< ::common::PID >
template<>
struct DataType< ::common::PIDRequest>
{
  static const char* value()
  {
    return DataType< ::common::PID >::value();
  }
  static const char* value(const ::common::PIDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common::PIDResponse> should match
// service_traits::MD5Sum< ::common::PID >
template<>
struct MD5Sum< ::common::PIDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common::PID >::value();
  }
  static const char* value(const ::common::PIDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::PIDResponse> should match
// service_traits::DataType< ::common::PID >
template<>
struct DataType< ::common::PIDResponse>
{
  static const char* value()
  {
    return DataType< ::common::PID >::value();
  }
  static const char* value(const ::common::PIDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MESSAGE_PID_H
