// Generated by gencpp from file common/PositionControlRequest.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_POSITIONCONTROLREQUEST_H
#define COMMON_MESSAGE_POSITIONCONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common
{
template <class ContainerAllocator>
struct PositionControlRequest_
{
  typedef PositionControlRequest_<ContainerAllocator> Type;

  PositionControlRequest_()
    : position_control_type(0)
    , target_position_f(0.0)
    , velocity_f(0.0)  {
    }
  PositionControlRequest_(const ContainerAllocator& _alloc)
    : position_control_type(0)
    , target_position_f(0.0)
    , velocity_f(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _position_control_type_type;
  _position_control_type_type position_control_type;

   typedef float _target_position_f_type;
  _target_position_f_type target_position_f;

   typedef float _velocity_f_type;
  _velocity_f_type velocity_f;





  typedef boost::shared_ptr< ::common::PositionControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::PositionControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PositionControlRequest_

typedef ::common::PositionControlRequest_<std::allocator<void> > PositionControlRequest;

typedef boost::shared_ptr< ::common::PositionControlRequest > PositionControlRequestPtr;
typedef boost::shared_ptr< ::common::PositionControlRequest const> PositionControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::PositionControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::PositionControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::PositionControlRequest_<ContainerAllocator1> & lhs, const ::common::PositionControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.position_control_type == rhs.position_control_type &&
    lhs.target_position_f == rhs.target_position_f &&
    lhs.velocity_f == rhs.velocity_f;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::PositionControlRequest_<ContainerAllocator1> & lhs, const ::common::PositionControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::PositionControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::PositionControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::PositionControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::PositionControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::PositionControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::PositionControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::PositionControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b361bcfd5b1a1843f6bad475de30172";
  }

  static const char* value(const ::common::PositionControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b361bcfd5b1a184ULL;
  static const uint64_t static_value2 = 0x3f6bad475de30172ULL;
};

template<class ContainerAllocator>
struct DataType< ::common::PositionControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/PositionControlRequest";
  }

  static const char* value(const ::common::PositionControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::PositionControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 position_control_type #0表示绝对位置 1表示相对位置\n"
"float32 target_position_f #目标位置 单位：mm\n"
"float32 velocity_f #速度 单位mm/s\n"
;
  }

  static const char* value(const ::common::PositionControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::PositionControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position_control_type);
      stream.next(m.target_position_f);
      stream.next(m.velocity_f);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::PositionControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::PositionControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "position_control_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position_control_type);
    s << indent << "target_position_f: ";
    Printer<float>::stream(s, indent + "  ", v.target_position_f);
    s << indent << "velocity_f: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_f);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_POSITIONCONTROLREQUEST_H
