// Generated by gencpp from file common/RecordPosition.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_RECORDPOSITION_H
#define COMMON_MESSAGE_RECORDPOSITION_H

#include <ros/service_traits.h>


#include <common/RecordPositionRequest.h>
#include <common/RecordPositionResponse.h>


namespace common
{

struct RecordPosition
{

typedef RecordPositionRequest Request;
typedef RecordPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RecordPosition
} // namespace common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common::RecordPosition > {
  static const char* value()
  {
    return "7b0729f31458f38616908a68952d309b";
  }

  static const char* value(const ::common::RecordPosition&) { return value(); }
};

template<>
struct DataType< ::common::RecordPosition > {
  static const char* value()
  {
    return "common/RecordPosition";
  }

  static const char* value(const ::common::RecordPosition&) { return value(); }
};


// service_traits::MD5Sum< ::common::RecordPositionRequest> should match
// service_traits::MD5Sum< ::common::RecordPosition >
template<>
struct MD5Sum< ::common::RecordPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common::RecordPosition >::value();
  }
  static const char* value(const ::common::RecordPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::RecordPositionRequest> should match
// service_traits::DataType< ::common::RecordPosition >
template<>
struct DataType< ::common::RecordPositionRequest>
{
  static const char* value()
  {
    return DataType< ::common::RecordPosition >::value();
  }
  static const char* value(const ::common::RecordPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common::RecordPositionResponse> should match
// service_traits::MD5Sum< ::common::RecordPosition >
template<>
struct MD5Sum< ::common::RecordPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common::RecordPosition >::value();
  }
  static const char* value(const ::common::RecordPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::RecordPositionResponse> should match
// service_traits::DataType< ::common::RecordPosition >
template<>
struct DataType< ::common::RecordPositionResponse>
{
  static const char* value()
  {
    return DataType< ::common::RecordPosition >::value();
  }
  static const char* value(const ::common::RecordPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MESSAGE_RECORDPOSITION_H
