// Generated by gencpp from file common/ResetMap.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_RESETMAP_H
#define COMMON_MESSAGE_RESETMAP_H

#include <ros/service_traits.h>


#include <common/ResetMapRequest.h>
#include <common/ResetMapResponse.h>


namespace common
{

struct ResetMap
{

typedef ResetMapRequest Request;
typedef ResetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetMap
} // namespace common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common::ResetMap > {
  static const char* value()
  {
    return "9fabf1eaf267dccbe2dae60c58619584";
  }

  static const char* value(const ::common::ResetMap&) { return value(); }
};

template<>
struct DataType< ::common::ResetMap > {
  static const char* value()
  {
    return "common/ResetMap";
  }

  static const char* value(const ::common::ResetMap&) { return value(); }
};


// service_traits::MD5Sum< ::common::ResetMapRequest> should match
// service_traits::MD5Sum< ::common::ResetMap >
template<>
struct MD5Sum< ::common::ResetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common::ResetMap >::value();
  }
  static const char* value(const ::common::ResetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::ResetMapRequest> should match
// service_traits::DataType< ::common::ResetMap >
template<>
struct DataType< ::common::ResetMapRequest>
{
  static const char* value()
  {
    return DataType< ::common::ResetMap >::value();
  }
  static const char* value(const ::common::ResetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common::ResetMapResponse> should match
// service_traits::MD5Sum< ::common::ResetMap >
template<>
struct MD5Sum< ::common::ResetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common::ResetMap >::value();
  }
  static const char* value(const ::common::ResetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::ResetMapResponse> should match
// service_traits::DataType< ::common::ResetMap >
template<>
struct DataType< ::common::ResetMapResponse>
{
  static const char* value()
  {
    return DataType< ::common::ResetMap >::value();
  }
  static const char* value(const ::common::ResetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MESSAGE_RESETMAP_H
