// Generated by gencpp from file common/setposition_control.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_SETPOSITION_CONTROL_H
#define COMMON_MESSAGE_SETPOSITION_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common
{
template <class ContainerAllocator>
struct setposition_control_
{
  typedef setposition_control_<ContainerAllocator> Type;

  setposition_control_()
    : target_position_f(0.0)  {
    }
  setposition_control_(const ContainerAllocator& _alloc)
    : target_position_f(0.0)  {
  (void)_alloc;
    }



   typedef float _target_position_f_type;
  _target_position_f_type target_position_f;





  typedef boost::shared_ptr< ::common::setposition_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::setposition_control_<ContainerAllocator> const> ConstPtr;

}; // struct setposition_control_

typedef ::common::setposition_control_<std::allocator<void> > setposition_control;

typedef boost::shared_ptr< ::common::setposition_control > setposition_controlPtr;
typedef boost::shared_ptr< ::common::setposition_control const> setposition_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::setposition_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::setposition_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::setposition_control_<ContainerAllocator1> & lhs, const ::common::setposition_control_<ContainerAllocator2> & rhs)
{
  return lhs.target_position_f == rhs.target_position_f;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::setposition_control_<ContainerAllocator1> & lhs, const ::common::setposition_control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::setposition_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::setposition_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::setposition_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::setposition_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::setposition_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::setposition_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::setposition_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2e6bf020ed2049abd8afb50018d662c";
  }

  static const char* value(const ::common::setposition_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2e6bf020ed2049aULL;
  static const uint64_t static_value2 = 0xbd8afb50018d662cULL;
};

template<class ContainerAllocator>
struct DataType< ::common::setposition_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/setposition_control";
  }

  static const char* value(const ::common::setposition_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::setposition_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 设置位置\n"
"float32 target_position_f #目标位置 单位：mm\n"
;
  }

  static const char* value(const ::common::setposition_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::setposition_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_position_f);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setposition_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::setposition_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::setposition_control_<ContainerAllocator>& v)
  {
    s << indent << "target_position_f: ";
    Printer<float>::stream(s, indent + "  ", v.target_position_f);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_SETPOSITION_CONTROL_H
