// Generated by gencpp from file common/TakePictureResponse.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_TAKEPICTURERESPONSE_H
#define COMMON_MESSAGE_TAKEPICTURERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace common
{
template <class ContainerAllocator>
struct TakePictureResponse_
{
  typedef TakePictureResponse_<ContainerAllocator> Type;

  TakePictureResponse_()
    : img()
    , status_code(0)
    , err_msg()  {
    }
  TakePictureResponse_(const ContainerAllocator& _alloc)
    : img(_alloc)
    , status_code(0)
    , err_msg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img_type;
  _img_type img;

   typedef int32_t _status_code_type;
  _status_code_type status_code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _err_msg_type;
  _err_msg_type err_msg;





  typedef boost::shared_ptr< ::common::TakePictureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::TakePictureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TakePictureResponse_

typedef ::common::TakePictureResponse_<std::allocator<void> > TakePictureResponse;

typedef boost::shared_ptr< ::common::TakePictureResponse > TakePictureResponsePtr;
typedef boost::shared_ptr< ::common::TakePictureResponse const> TakePictureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::TakePictureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::TakePictureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::TakePictureResponse_<ContainerAllocator1> & lhs, const ::common::TakePictureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.img == rhs.img &&
    lhs.status_code == rhs.status_code &&
    lhs.err_msg == rhs.err_msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::TakePictureResponse_<ContainerAllocator1> & lhs, const ::common::TakePictureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::TakePictureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::TakePictureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::TakePictureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::TakePictureResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::TakePictureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::TakePictureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::TakePictureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9043ad6543908764c35c3fb41997ccd4";
  }

  static const char* value(const ::common::TakePictureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9043ad6543908764ULL;
  static const uint64_t static_value2 = 0xc35c3fb41997ccd4ULL;
};

template<class ContainerAllocator>
struct DataType< ::common::TakePictureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/TakePictureResponse";
  }

  static const char* value(const ::common::TakePictureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::TakePictureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image img\n"
"int32 status_code #0失败，1完成\n"
"string err_msg\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::common::TakePictureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::TakePictureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.img);
      stream.next(m.status_code);
      stream.next(m.err_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TakePictureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::TakePictureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::TakePictureResponse_<ContainerAllocator>& v)
  {
    s << indent << "img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img);
    s << indent << "status_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status_code);
    s << indent << "err_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.err_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_TAKEPICTURERESPONSE_H
