// Generated by gencpp from file common/VelocityControl.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_VELOCITYCONTROL_H
#define COMMON_MESSAGE_VELOCITYCONTROL_H

#include <ros/service_traits.h>


#include <common/VelocityControlRequest.h>
#include <common/VelocityControlResponse.h>


namespace common
{

struct VelocityControl
{

typedef VelocityControlRequest Request;
typedef VelocityControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VelocityControl
} // namespace common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common::VelocityControl > {
  static const char* value()
  {
    return "c2220f86ebacca2a046f47fb48d0d40f";
  }

  static const char* value(const ::common::VelocityControl&) { return value(); }
};

template<>
struct DataType< ::common::VelocityControl > {
  static const char* value()
  {
    return "common/VelocityControl";
  }

  static const char* value(const ::common::VelocityControl&) { return value(); }
};


// service_traits::MD5Sum< ::common::VelocityControlRequest> should match
// service_traits::MD5Sum< ::common::VelocityControl >
template<>
struct MD5Sum< ::common::VelocityControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common::VelocityControl >::value();
  }
  static const char* value(const ::common::VelocityControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::VelocityControlRequest> should match
// service_traits::DataType< ::common::VelocityControl >
template<>
struct DataType< ::common::VelocityControlRequest>
{
  static const char* value()
  {
    return DataType< ::common::VelocityControl >::value();
  }
  static const char* value(const ::common::VelocityControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common::VelocityControlResponse> should match
// service_traits::MD5Sum< ::common::VelocityControl >
template<>
struct MD5Sum< ::common::VelocityControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common::VelocityControl >::value();
  }
  static const char* value(const ::common::VelocityControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::VelocityControlResponse> should match
// service_traits::DataType< ::common::VelocityControl >
template<>
struct DataType< ::common::VelocityControlResponse>
{
  static const char* value()
  {
    return DataType< ::common::VelocityControl >::value();
  }
  static const char* value(const ::common::VelocityControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MESSAGE_VELOCITYCONTROL_H
