// Generated by gencpp from file common/VideoDataRequest.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_VIDEODATAREQUEST_H
#define COMMON_MESSAGE_VIDEODATAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/UInt8MultiArray.h>

namespace common
{
template <class ContainerAllocator>
struct VideoDataRequest_
{
  typedef VideoDataRequest_<ContainerAllocator> Type;

  VideoDataRequest_()
    : patrol_task_name()
    , patrol_section_index(0)
    , video_data()  {
    }
  VideoDataRequest_(const ContainerAllocator& _alloc)
    : patrol_task_name(_alloc)
    , patrol_section_index(0)
    , video_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _patrol_task_name_type;
  _patrol_task_name_type patrol_task_name;

   typedef int32_t _patrol_section_index_type;
  _patrol_section_index_type patrol_section_index;

   typedef  ::std_msgs::UInt8MultiArray_<ContainerAllocator>  _video_data_type;
  _video_data_type video_data;





  typedef boost::shared_ptr< ::common::VideoDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::VideoDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VideoDataRequest_

typedef ::common::VideoDataRequest_<std::allocator<void> > VideoDataRequest;

typedef boost::shared_ptr< ::common::VideoDataRequest > VideoDataRequestPtr;
typedef boost::shared_ptr< ::common::VideoDataRequest const> VideoDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::VideoDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::VideoDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::VideoDataRequest_<ContainerAllocator1> & lhs, const ::common::VideoDataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.patrol_task_name == rhs.patrol_task_name &&
    lhs.patrol_section_index == rhs.patrol_section_index &&
    lhs.video_data == rhs.video_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::VideoDataRequest_<ContainerAllocator1> & lhs, const ::common::VideoDataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::VideoDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::VideoDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::VideoDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::VideoDataRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::VideoDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::VideoDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::VideoDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f77074461472da68d7f62f138ae987a";
  }

  static const char* value(const ::common::VideoDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f77074461472da6ULL;
  static const uint64_t static_value2 = 0x8d7f62f138ae987aULL;
};

template<class ContainerAllocator>
struct DataType< ::common::VideoDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/VideoDataRequest";
  }

  static const char* value(const ::common::VideoDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::VideoDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string patrol_task_name     #连续巡检任务名称 写在patrolsections节点的Intro\n"
"int32 patrol_section_index\n"
"std_msgs/UInt8MultiArray video_data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt8MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"uint8[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::common::VideoDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::VideoDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.patrol_task_name);
      stream.next(m.patrol_section_index);
      stream.next(m.video_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VideoDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::VideoDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::VideoDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "patrol_task_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.patrol_task_name);
    s << indent << "patrol_section_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.patrol_section_index);
    s << indent << "video_data: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.video_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_VIDEODATAREQUEST_H
