version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: app
    image: app:latest
    restart: always
    container_name: app
    environment:
      ROS_MASTER_URI: http://ros_core:11311 #TODO replace the real ros master uri
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - ros_core
    # user: ubuntu
    command: python3 app/main.py
  
  celery-worker:
    image: app:latest
    command: celery -A app.celery_app.celery worker --loglevel=info
    volumes:
      - ./:/app
    environment:
      REDIS_PASSWORD: sample_password
      ROS_MASTER_URI: http://ros_core:11311 #TODO replace the real ros master uri
    # user: ubuntu
    depends_on:
      - redis

  
  db:
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: "sample_db"
      MYSQL_USER: "sample_user"
      MYSQL_PASSWORD: "sample_password"
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
      - "3306:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    
  ros_core:
    build: 
      context: .
      dockerfile: Dockerfile
      target: ros_core
    image: ros_core:latest
    restart: always
    container_name: ros_core
    # user: ubuntu
    depends_on: 
      - db

  redis:
    image: redis:latest
    # restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass "sample_password"
    

volumes:
  db_data: {}
  redis_data: {}