version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: app
    image: app:latest
    restart: always
    container_name: app
    environment:
      ROS_MASTER_URI: http://ros_core:11311 
      REDIS_PASSWORD: sample_password
      ROS_HOSTNAME: 192.168.2.43
      PYTHONPATH : /app/share/devel/lib/python3/dist-packages
      VISION_ALGORITHM_API_URL: http://192.168.2.41:5209
    ports:
      - "8000:8000"
      - "45150-45200:45150-45200"
    volumes:
      - ./:/app
      - ./app/time_setting/timezone:/etc/timezone:ro
      - ./app/time_setting/localtime:/etc/localtime:ro
      - video_data:/app/app/static/videos
    depends_on:
      - db
      - redis
      - ros_core
    logging:
      driver: "json-file"
      options:
          max-size: "1g"

    command: python3 app/main.py
  
  celery-worker:
    container_name: celery-worker
    restart: always
    image: app:latest
    command: celery -A app.celery_app.celery worker -B --loglevel=warning
    volumes:
      - ./:/app
      - ./app/time_setting/timezone:/etc/timezone:ro
      - ./app/time_setting/localtime:/etc/localtime:ro

    environment:
      REDIS_PASSWORD: sample_password
      ROS_MASTER_URI: http://ros_core:11311 
      PYTHONPATH : /app/share/devel/lib/python3/dist-packages
      VISION_ALGORITHM_API_URL: http://192.168.2.41:5209
    depends_on:
      - db
      - redis
    logging:
      driver: "json-file"
      options:
          max-size: "1g"

  
  db:
    image: "mysql:8.0"
    container_name: db
    environment:
      MYSQL_DATABASE: "sample_db"
      MYSQL_USER: "sample_user"
      MYSQL_PASSWORD: "sample_password"
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    
  ros_core:
    build: 
      context: .
      dockerfile: Dockerfile
      target: ros_core
    image: ros_core:latest
    restart: always
    container_name: ros_core
    hostname: ros_core
    ports:
      - "11311:11311"
    depends_on: 
      - db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly no --requirepass "sample_password"
    
  panorama_video_website:
    image: nginx:latest
    container_name: panorama_video_website
    ports:
      - "80:80"  
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./panorama_video_website/conf.d:/etc/nginx/conf.d
      - ./panorama_video_website/UtoVRPlayerSDK_1.0.1194_Web:/UtoVRPlayerSDK_1.0.1194_Web
      - video_data:/UtoVRPlayerSDK_1.0.1194_Web/sample/videos/
    restart: always



volumes:
  video_data: {}
  mysql_data: {}
  redis_data: {}