version: '3.9'

services:
  app:
    build: .
    image: app:latest
    restart: always
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - dynamic_bridge

  
  db:
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: "sample_db"
      MYSQL_USER: "sample_user"
      MYSQL_PASSWORD: "sample_password"
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
      - "3306:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    
  dynamic_bridge:
    image: dynamic_bridge:latest
    restart: always
    container_name: dynamic_bridge
    environment:
      ROS_MASTER_URI: http://app:11311 #TODO replace the real ros master uri
    depends_on: 
      - db
    

volumes:
  db_data: {}