(cl:defpackage common-srv
  (:use )
  (:export
   "POSITIONCONTROL"
   "<POSITIONCONTROL-REQUEST>"
   "POSITIONCONTROL-REQUEST"
   "<POSITIONCONTROL-RESPONSE>"
   "POSITIONCONTROL-RESPONSE"
   "STOPCONTROL"
   "<STOPCONTROL-REQUEST>"
   "STOPCONTROL-REQUEST"
   "<STOPCONTROL-RESPONSE>"
   "STOPCONTROL-RESPONSE"
   "TAKEPICTURE"
   "<TAKEPICTURE-REQUEST>"
   "TAKEPICTURE-REQUEST"
   "<TAKEPICTURE-RESPONSE>"
   "TAKEPICTURE-RESPONSE"
   "VELOCITYCONTROL"
   "<VELOCITYCONTROL-REQUEST>"
   "VELOCITYCONTROL-REQUEST"
   "<VELOCITYCONTROL-RESPONSE>"
   "VELOCITYCONTROL-RESPONSE"
  ))

