; Auto-generated. Do not edit!


(cl:in-package zj_robot-msg)


;//! \htmlinclude motion_controlFeedback.msg.html

(cl:defclass <motion_controlFeedback> (roslisp-msg-protocol:ros-message)
  ((position
    :reader position
    :initarg :position
    :type cl:float
    :initform 0.0)
   (velocity
    :reader velocity
    :initarg :velocity
    :type cl:float
    :initform 0.0))
)

(cl:defclass motion_controlFeedback (<motion_controlFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <motion_controlFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'motion_controlFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name zj_robot-msg:<motion_controlFeedback> is deprecated: use zj_robot-msg:motion_controlFeedback instead.")))

(cl:ensure-generic-function 'position-val :lambda-list '(m))
(cl:defmethod position-val ((m <motion_controlFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader zj_robot-msg:position-val is deprecated.  Use zj_robot-msg:position instead.")
  (position m))

(cl:ensure-generic-function 'velocity-val :lambda-list '(m))
(cl:defmethod velocity-val ((m <motion_controlFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader zj_robot-msg:velocity-val is deprecated.  Use zj_robot-msg:velocity instead.")
  (velocity m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <motion_controlFeedback>) ostream)
  "Serializes a message object of type '<motion_controlFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'position))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'velocity))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <motion_controlFeedback>) istream)
  "Deserializes a message object of type '<motion_controlFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'position) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'velocity) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<motion_controlFeedback>)))
  "Returns string type for a message object of type '<motion_controlFeedback>"
  "zj_robot/motion_controlFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'motion_controlFeedback)))
  "Returns string type for a message object of type 'motion_controlFeedback"
  "zj_robot/motion_controlFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<motion_controlFeedback>)))
  "Returns md5sum for a message object of type '<motion_controlFeedback>"
  "2cf6c2ef6d4814960f7bd2c448525593")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'motion_controlFeedback)))
  "Returns md5sum for a message object of type 'motion_controlFeedback"
  "2cf6c2ef6d4814960f7bd2c448525593")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<motion_controlFeedback>)))
  "Returns full string definition for message of type '<motion_controlFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#连续位置 速度反馈~%float32 position~%float32 velocity~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'motion_controlFeedback)))
  "Returns full string definition for message of type 'motion_controlFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#连续位置 速度反馈~%float32 position~%float32 velocity~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <motion_controlFeedback>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <motion_controlFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'motion_controlFeedback
    (cl:cons ':position (position msg))
    (cl:cons ':velocity (velocity msg))
))
