# Define a dictionary that maps each key to its corresponding Chinese translation
key_map = {
    "name": "名称",
    "position": "位置",
    "velocity": "速度",
    "gimbal_points": "云台点",
    "preset_index": "预设点",
    "robot_id": "机器人ID",
    "total_distance": "总里程",
    "total_task_executed": "总任务执行数",
    "total_alarm_raised": "总报警次数",
    "battery": "电量",
    "battery_status": "电池状态",
    "status": "状态",
    "task_id": "任务ID",
    "task_status": "任务状态",
    "sensors": "传感器",
    "value": "数值",
    "type": "类型",
    "checkpoint_ids": "检查点ID",
    "start_position": "起始位置",
    "end_position": "结束位置",
    "vision_algorithms": "视觉算法",
    "execution_time": "执行时间",
    "unit": "单位",
    "level": "等级",
    "location": "位置",
    "time": "时间",
    "upper_limit": "上限",
    "lower_limit": "下限",
    "sensitivity": "灵敏度",
}

value_map = {
    "temperature": "温度",
    "humidity": "湿度",
    "light": "光照",
    "smoke1": "烟雾1",
    "smoke2": "烟雾2",
}
