// Auto-generated. Do not edit!

// (in-package zj_robot.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class motion_controlResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.inposition = null;
    }
    else {
      if (initObj.hasOwnProperty('inposition')) {
        this.inposition = initObj.inposition
      }
      else {
        this.inposition = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type motion_controlResult
    // Serialize message field [inposition]
    bufferOffset = _serializer.bool(obj.inposition, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type motion_controlResult
    let len;
    let data = new motion_controlResult(null);
    // Deserialize message field [inposition]
    data.inposition = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'zj_robot/motion_controlResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1a33a407c88c263cad076c785a4007a1';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #是否到达指定位置
    bool inposition
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new motion_controlResult(null);
    if (msg.inposition !== undefined) {
      resolved.inposition = msg.inposition;
    }
    else {
      resolved.inposition = false
    }

    return resolved;
    }
};

module.exports = motion_controlResult;
