// Auto-generated. Do not edit!

// (in-package zj_robot.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class motion_controlGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.ABSorREL = null;
      this.target_position = null;
      this.velocity = null;
    }
    else {
      if (initObj.hasOwnProperty('ABSorREL')) {
        this.ABSorREL = initObj.ABSorREL
      }
      else {
        this.ABSorREL = 0;
      }
      if (initObj.hasOwnProperty('target_position')) {
        this.target_position = initObj.target_position
      }
      else {
        this.target_position = 0;
      }
      if (initObj.hasOwnProperty('velocity')) {
        this.velocity = initObj.velocity
      }
      else {
        this.velocity = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type motion_controlGoal
    // Serialize message field [ABSorREL]
    bufferOffset = _serializer.int32(obj.ABSorREL, buffer, bufferOffset);
    // Serialize message field [target_position]
    bufferOffset = _serializer.int32(obj.target_position, buffer, bufferOffset);
    // Serialize message field [velocity]
    bufferOffset = _serializer.float32(obj.velocity, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type motion_controlGoal
    let len;
    let data = new motion_controlGoal(null);
    // Deserialize message field [ABSorREL]
    data.ABSorREL = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [target_position]
    data.target_position = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [velocity]
    data.velocity = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'zj_robot/motion_controlGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'ca92a3bf81e86dbf05d6be4d70513968';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #位置控制action
    
    #目标位置 单位m
    int32 ABSorREL #相对或绝对
    int32 target_position
    float32 velocity
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new motion_controlGoal(null);
    if (msg.ABSorREL !== undefined) {
      resolved.ABSorREL = msg.ABSorREL;
    }
    else {
      resolved.ABSorREL = 0
    }

    if (msg.target_position !== undefined) {
      resolved.target_position = msg.target_position;
    }
    else {
      resolved.target_position = 0
    }

    if (msg.velocity !== undefined) {
      resolved.velocity = msg.velocity;
    }
    else {
      resolved.velocity = 0.0
    }

    return resolved;
    }
};

module.exports = motion_controlGoal;
