"""empty message

Revision ID: 1bcb3ad88c16
Revises: 
Create Date: 2023-05-05 02:17:33.747089

"""


# revision identifiers, used by Alembic.
revision = '1bcb3ad88c16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
