"""empty message

Revision ID: 26af8e0c95a5
Revises: 
Create Date: 2023-05-05 09:37:16.802709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26af8e0c95a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot_logs', sa.Column('robot_name', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_robot_logs_robot_name'), 'robot_logs', ['robot_name'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_robot_logs_robot_name'), table_name='robot_logs')
    op.drop_column('robot_logs', 'robot_name')
    # ### end Alembic commands ###
