"""empty message

Revision ID: 34fcfffdad1a
Revises: d295739d61e8
Create Date: 2023-05-05 10:43:54.562218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34fcfffdad1a'
down_revision = 'd295739d61e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'lower_limit')
    op.drop_column('sensors', 'upper_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('upper_limit', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sensors', sa.Column('lower_limit', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
