"""empty message

Revision ID: 6723fec49fa8
Revises: 7204194a2cc5
Create Date: 2023-05-06 05:57:43.022426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6723fec49fa8'
down_revision = '7204194a2cc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
