"""empty message

Revision ID: 7204194a2cc5
Revises: 34fcfffdad1a
Create Date: 2023-05-05 10:44:04.309585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7204194a2cc5'
down_revision = '34fcfffdad1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('upper_limit', sa.Float(), nullable=True))
    op.add_column('sensors', sa.Column('lower_limit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'lower_limit')
    op.drop_column('sensors', 'upper_limit')
    # ### end Alembic commands ###
