"""empty message

Revision ID: bade38baae7f
Revises: 7df918dc1862
Create Date: 2023-05-05 10:40:09.348182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bade38baae7f'
down_revision = '7df918dc1862'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
