"""empty message

Revision ID: d295739d61e8
Revises: 16ddfa6c64d2
Create Date: 2023-05-05 10:43:37.973062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd295739d61e8'
down_revision = '16ddfa6c64d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
