"""empty message

Revision ID: d36d24e05d16
Revises: d8e5007506af
Create Date: 2023-05-16 03:31:50.429501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36d24e05d16'
down_revision = 'd8e5007506af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
