"""empty message

Revision ID: f04b6ec75947
Revises: 88f7b427eb34
Create Date: 2023-05-05 06:25:31.641719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04b6ec75947'
down_revision = '88f7b427eb34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sensors_ibfk_1', 'sensors', type_='foreignkey')
    op.create_foreign_key(None, 'sensors', 'robots', ['robot_id'], ['id'])
    op.drop_constraint('tasks_ibfk_1', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'robots', ['robot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_ibfk_1', 'tasks', 'robots', ['robot_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sensors', type_='foreignkey')
    op.create_foreign_key('sensors_ibfk_1', 'sensors', 'robots', ['robot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
