"""empty message

Revision ID: fa57d51ed397
Revises: b8cbeb153d37
Create Date: 2023-05-06 09:23:20.381752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa57d51ed397'
down_revision = 'b8cbeb153d37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'upper_limit')
    op.drop_column('sensors', 'lower_limit')
    op.drop_column('vision_algorithms', 'sensitivity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vision_algorithms', sa.Column('sensitivity', mysql.FLOAT(), nullable=True))
    op.add_column('sensors', sa.Column('lower_limit', mysql.FLOAT(), nullable=True))
    op.add_column('sensors', sa.Column('upper_limit', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
