// Generated by gencpp from file zj_robot/motion_controlActionGoal.msg
// DO NOT EDIT!


#ifndef ZJ_ROBOT_MESSAGE_MOTION_CONTROLACTIONGOAL_H
#define ZJ_ROBOT_MESSAGE_MOTION_CONTROLACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <zj_robot/motion_controlGoal.h>

namespace zj_robot
{
template <class ContainerAllocator>
struct motion_controlActionGoal_
{
  typedef motion_controlActionGoal_<ContainerAllocator> Type;

  motion_controlActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  motion_controlActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::zj_robot::motion_controlGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct motion_controlActionGoal_

typedef ::zj_robot::motion_controlActionGoal_<std::allocator<void> > motion_controlActionGoal;

typedef boost::shared_ptr< ::zj_robot::motion_controlActionGoal > motion_controlActionGoalPtr;
typedef boost::shared_ptr< ::zj_robot::motion_controlActionGoal const> motion_controlActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zj_robot::motion_controlActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::zj_robot::motion_controlActionGoal_<ContainerAllocator1> & lhs, const ::zj_robot::motion_controlActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::zj_robot::motion_controlActionGoal_<ContainerAllocator1> & lhs, const ::zj_robot::motion_controlActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace zj_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "926c1caf6b136a780fbaa250fba2b033";
  }

  static const char* value(const ::zj_robot::motion_controlActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x926c1caf6b136a78ULL;
  static const uint64_t static_value2 = 0x0fbaa250fba2b033ULL;
};

template<class ContainerAllocator>
struct DataType< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zj_robot/motion_controlActionGoal";
  }

  static const char* value(const ::zj_robot::motion_controlActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"motion_controlGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: zj_robot/motion_controlGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#位置控制action\n"
"\n"
"#目标位置 单位m\n"
"int32 ABSorREL #相对或绝对\n"
"int32 target_position\n"
"float32 velocity\n"
;
  }

  static const char* value(const ::zj_robot::motion_controlActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motion_controlActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zj_robot::motion_controlActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::zj_robot::motion_controlGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZJ_ROBOT_MESSAGE_MOTION_CONTROLACTIONGOAL_H
