// Generated by gencpp from file ros_interfaces/stop_command.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACES_MESSAGE_STOP_COMMAND_H
#define ROS_INTERFACES_MESSAGE_STOP_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_interfaces
{
template <class ContainerAllocator>
struct stop_command_
{
  typedef stop_command_<ContainerAllocator> Type;

  stop_command_()
    : stop_type(0)  {
    }
  stop_command_(const ContainerAllocator& _alloc)
    : stop_type(0)  {
  (void)_alloc;
    }



   typedef int32_t _stop_type_type;
  _stop_type_type stop_type;





  typedef boost::shared_ptr< ::ros_interfaces::stop_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interfaces::stop_command_<ContainerAllocator> const> ConstPtr;

}; // struct stop_command_

typedef ::ros_interfaces::stop_command_<std::allocator<void> > stop_command;

typedef boost::shared_ptr< ::ros_interfaces::stop_command > stop_commandPtr;
typedef boost::shared_ptr< ::ros_interfaces::stop_command const> stop_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interfaces::stop_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interfaces::stop_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interfaces::stop_command_<ContainerAllocator1> & lhs, const ::ros_interfaces::stop_command_<ContainerAllocator2> & rhs)
{
  return lhs.stop_type == rhs.stop_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interfaces::stop_command_<ContainerAllocator1> & lhs, const ::ros_interfaces::stop_command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interfaces::stop_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interfaces::stop_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interfaces::stop_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interfaces::stop_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interfaces::stop_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interfaces::stop_command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interfaces::stop_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b6fac8d08de0982f05ab0aa2f3aa6b5";
  }

  static const char* value(const ::ros_interfaces::stop_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b6fac8d08de0982ULL;
  static const uint64_t static_value2 = 0xf05ab0aa2f3aa6b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interfaces::stop_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interfaces/stop_command";
  }

  static const char* value(const ::ros_interfaces::stop_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interfaces::stop_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 stop_type #0 stop 1 stop 2 kill\n"
;
  }

  static const char* value(const ::ros_interfaces::stop_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interfaces::stop_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stop_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stop_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interfaces::stop_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interfaces::stop_command_<ContainerAllocator>& v)
  {
    s << indent << "stop_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.stop_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACES_MESSAGE_STOP_COMMAND_H
