// Generated by gencpp from file zj_robot/motion_controlAction.msg
// DO NOT EDIT!


#ifndef ZJ_ROBOT_MESSAGE_MOTION_CONTROLACTION_H
#define ZJ_ROBOT_MESSAGE_MOTION_CONTROLACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <zj_robot/motion_controlActionGoal.h>
#include <zj_robot/motion_controlActionResult.h>
#include <zj_robot/motion_controlActionFeedback.h>

namespace zj_robot
{
template <class ContainerAllocator>
struct motion_controlAction_
{
  typedef motion_controlAction_<ContainerAllocator> Type;

  motion_controlAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  motion_controlAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::zj_robot::motion_controlActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::zj_robot::motion_controlActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::zj_robot::motion_controlActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::zj_robot::motion_controlAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zj_robot::motion_controlAction_<ContainerAllocator> const> ConstPtr;

}; // struct motion_controlAction_

typedef ::zj_robot::motion_controlAction_<std::allocator<void> > motion_controlAction;

typedef boost::shared_ptr< ::zj_robot::motion_controlAction > motion_controlActionPtr;
typedef boost::shared_ptr< ::zj_robot::motion_controlAction const> motion_controlActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zj_robot::motion_controlAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zj_robot::motion_controlAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::zj_robot::motion_controlAction_<ContainerAllocator1> & lhs, const ::zj_robot::motion_controlAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::zj_robot::motion_controlAction_<ContainerAllocator1> & lhs, const ::zj_robot::motion_controlAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace zj_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::zj_robot::motion_controlAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zj_robot::motion_controlAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zj_robot::motion_controlAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zj_robot::motion_controlAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zj_robot::motion_controlAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zj_robot::motion_controlAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zj_robot::motion_controlAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05ccdb15e390725e3d2c26e9e6dc6993";
  }

  static const char* value(const ::zj_robot::motion_controlAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05ccdb15e390725eULL;
  static const uint64_t static_value2 = 0x3d2c26e9e6dc6993ULL;
};

template<class ContainerAllocator>
struct DataType< ::zj_robot::motion_controlAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zj_robot/motion_controlAction";
  }

  static const char* value(const ::zj_robot::motion_controlAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zj_robot::motion_controlAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"motion_controlActionGoal action_goal\n"
"motion_controlActionResult action_result\n"
"motion_controlActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: zj_robot/motion_controlActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"motion_controlGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: zj_robot/motion_controlGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#位置控制action\n"
"\n"
"#目标位置 单位m\n"
"int32 ABSorREL #相对或绝对\n"
"int32 target_position\n"
"float32 velocity\n"
"\n"
"================================================================================\n"
"MSG: zj_robot/motion_controlActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"motion_controlResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: zj_robot/motion_controlResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#是否到达指定位置\n"
"bool inposition\n"
"\n"
"================================================================================\n"
"MSG: zj_robot/motion_controlActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"motion_controlFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: zj_robot/motion_controlFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#连续位置 速度反馈\n"
"float32 position\n"
"float32 velocity\n"
;
  }

  static const char* value(const ::zj_robot::motion_controlAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zj_robot::motion_controlAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motion_controlAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zj_robot::motion_controlAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zj_robot::motion_controlAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::zj_robot::motion_controlActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::zj_robot::motion_controlActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::zj_robot::motion_controlActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZJ_ROBOT_MESSAGE_MOTION_CONTROLACTION_H
