// Generated by gencpp from file ros_interfaces/gimbal_control.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACES_MESSAGE_GIMBAL_CONTROL_H
#define ROS_INTERFACES_MESSAGE_GIMBAL_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_interfaces
{
template <class ContainerAllocator>
struct gimbal_control_
{
  typedef gimbal_control_<ContainerAllocator> Type;

  gimbal_control_()
    : command(0)
    , preset_index(0)  {
    }
  gimbal_control_(const ContainerAllocator& _alloc)
    : command(0)
    , preset_index(0)  {
  (void)_alloc;
    }



   typedef int32_t _command_type;
  _command_type command;

   typedef int32_t _preset_index_type;
  _preset_index_type preset_index;





  typedef boost::shared_ptr< ::ros_interfaces::gimbal_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interfaces::gimbal_control_<ContainerAllocator> const> ConstPtr;

}; // struct gimbal_control_

typedef ::ros_interfaces::gimbal_control_<std::allocator<void> > gimbal_control;

typedef boost::shared_ptr< ::ros_interfaces::gimbal_control > gimbal_controlPtr;
typedef boost::shared_ptr< ::ros_interfaces::gimbal_control const> gimbal_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interfaces::gimbal_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interfaces::gimbal_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interfaces::gimbal_control_<ContainerAllocator1> & lhs, const ::ros_interfaces::gimbal_control_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.preset_index == rhs.preset_index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interfaces::gimbal_control_<ContainerAllocator1> & lhs, const ::ros_interfaces::gimbal_control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interfaces::gimbal_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interfaces::gimbal_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interfaces::gimbal_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interfaces::gimbal_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interfaces::gimbal_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interfaces::gimbal_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interfaces::gimbal_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9bd2fba3990c66b8df4336181b66716";
  }

  static const char* value(const ::ros_interfaces::gimbal_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9bd2fba3990c66bULL;
  static const uint64_t static_value2 = 0x8df4336181b66716ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interfaces::gimbal_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interfaces/gimbal_control";
  }

  static const char* value(const ::ros_interfaces::gimbal_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interfaces::gimbal_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 command #云台预置点命令\n"
"int32 preset_index #预置点编号\n"
;
  }

  static const char* value(const ::ros_interfaces::gimbal_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interfaces::gimbal_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.preset_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gimbal_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interfaces::gimbal_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interfaces::gimbal_control_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command);
    s << indent << "preset_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.preset_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACES_MESSAGE_GIMBAL_CONTROL_H
