string patrol_task_name     #巡检任务名称 写在patrolpoints节点的Intro
int32 patrol_point_index    #巡检点索引，从上往下从0开始
int32 gimbal_point_index    #云台运动预制点索引(不是预置点)，在某个巡检点从上往下从0开始
sensor_msgs/Image img       #图片
---
int32 status_code #0失败 1完成
