(cl:defpackage zj_robot-msg
  (:use )
  (:export
   "<MOTION_CONTROLACTION>"
   "MOTION_CONTROLACTION"
   "<MOTION_CONTROLACTIONFEEDBACK>"
   "MOTION_CONTROLACTIONFEEDBACK"
   "<MOTION_CONTROLACTIONGOAL>"
   "MOTION_CONTROLACTIONGOAL"
   "<MOTION_CONTROLACTIONRESULT>"
   "MOTION_CONTROLACTIONRESULT"
   "<MOTION_CONTROLFEEDBACK>"
   "MOTION_CONTROLFEEDBACK"
   "<MOTION_CONTROLGOAL>"
   "MOTION_CONTROLGOAL"
   "<MOTION_CONTROLRESULT>"
   "MOTION_CONTROLRESULT"
  ))

