(cl:defpackage common-msg
  (:use )
  (:export
   "<CAMERA_CONTROL>"
   "CAMERA_CONTROL"
   "<CHARGE_CONTROL>"
   "CHARGE_CONTROL"
   "<GIMBAL_CONTROL>"
   "GIMBAL_CONTROL"
   "<POSITION_CONTROL>"
   "POSITION_CONTROL"
   "<ROBOT_REAL_TIME_INFO>"
   "ROBOT_REAL_TIME_INFO"
   "<SENSOR_DATA>"
   "SENSOR_DATA"
   "<SETPOSITION_CONTROL>"
   "SETPOSITION_CONTROL"
   "<STOP_CONTROL>"
   "STOP_CONTROL"
   "<VELOCITY_CONTROL>"
   "VELOCITY_CONTROL"
   "<VOICE_CONTROL>"
   "VOICE_CONTROL"
  ))

