// Generated by gencpp from file common/FirmwareUpdateRequest.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_FIRMWAREUPDATEREQUEST_H
#define COMMON_MESSAGE_FIRMWAREUPDATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common
{
template <class ContainerAllocator>
struct FirmwareUpdateRequest_
{
  typedef FirmwareUpdateRequest_<ContainerAllocator> Type;

  FirmwareUpdateRequest_()
    : data()  {
    }
  FirmwareUpdateRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::common::FirmwareUpdateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::FirmwareUpdateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FirmwareUpdateRequest_

typedef ::common::FirmwareUpdateRequest_<std::allocator<void> > FirmwareUpdateRequest;

typedef boost::shared_ptr< ::common::FirmwareUpdateRequest > FirmwareUpdateRequestPtr;
typedef boost::shared_ptr< ::common::FirmwareUpdateRequest const> FirmwareUpdateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::FirmwareUpdateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::FirmwareUpdateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::FirmwareUpdateRequest_<ContainerAllocator1> & lhs, const ::common::FirmwareUpdateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::FirmwareUpdateRequest_<ContainerAllocator1> & lhs, const ::common::FirmwareUpdateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::FirmwareUpdateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::FirmwareUpdateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::FirmwareUpdateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::FirmwareUpdateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::FirmwareUpdateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::FirmwareUpdateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::FirmwareUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::common::FirmwareUpdateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992ce8a1687cec8cULL;
  static const uint64_t static_value2 = 0x8bd883ec73ca41d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::common::FirmwareUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/FirmwareUpdateRequest";
  }

  static const char* value(const ::common::FirmwareUpdateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::FirmwareUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n"
;
  }

  static const char* value(const ::common::FirmwareUpdateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::FirmwareUpdateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FirmwareUpdateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::FirmwareUpdateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::FirmwareUpdateRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_FIRMWAREUPDATEREQUEST_H
