// Generated by gencpp from file common/gimbal_motion_control.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_GIMBAL_MOTION_CONTROL_H
#define COMMON_MESSAGE_GIMBAL_MOTION_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common
{
template <class ContainerAllocator>
struct gimbal_motion_control_
{
  typedef gimbal_motion_control_<ContainerAllocator> Type;

  gimbal_motion_control_()
    : command(0)  {
    }
  gimbal_motion_control_(const ContainerAllocator& _alloc)
    : command(0)  {
  (void)_alloc;
    }



   typedef int32_t _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::common::gimbal_motion_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::gimbal_motion_control_<ContainerAllocator> const> ConstPtr;

}; // struct gimbal_motion_control_

typedef ::common::gimbal_motion_control_<std::allocator<void> > gimbal_motion_control;

typedef boost::shared_ptr< ::common::gimbal_motion_control > gimbal_motion_controlPtr;
typedef boost::shared_ptr< ::common::gimbal_motion_control const> gimbal_motion_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::gimbal_motion_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::gimbal_motion_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::gimbal_motion_control_<ContainerAllocator1> & lhs, const ::common::gimbal_motion_control_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::gimbal_motion_control_<ContainerAllocator1> & lhs, const ::common::gimbal_motion_control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::gimbal_motion_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::gimbal_motion_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::gimbal_motion_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::gimbal_motion_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::gimbal_motion_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::gimbal_motion_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::gimbal_motion_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a54bc0c5f4abe9ad44d29292ec0800d";
  }

  static const char* value(const ::common::gimbal_motion_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a54bc0c5f4abe9aULL;
  static const uint64_t static_value2 = 0xd44d29292ec0800dULL;
};

template<class ContainerAllocator>
struct DataType< ::common::gimbal_motion_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/gimbal_motion_control";
  }

  static const char* value(const ::common::gimbal_motion_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::gimbal_motion_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 command \n"
"#   云台运动命令及对应编号\n"
"#--------------------------------\n"
"# UP_LEFT   TILT_UP    UP_RIGHT\n"
"# PAN_LEFT             PAN_RIGHT\n"
"# DOWN_LEFT TILT_DOWN  DOWN_RIGHT\n"
"#--------------------------------\n"
"#   1         2          3\n"
"#   4                    6\n"
"#   7         8          9\n"
"#--------------------------------\n"
"\n"
"\n"
;
  }

  static const char* value(const ::common::gimbal_motion_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::gimbal_motion_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gimbal_motion_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::gimbal_motion_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::gimbal_motion_control_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_GIMBAL_MOTION_CONTROL_H
