// Generated by gencpp from file common/PanoramicVideoUrlResponse.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_PANORAMICVIDEOURLRESPONSE_H
#define COMMON_MESSAGE_PANORAMICVIDEOURLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common
{
template <class ContainerAllocator>
struct PanoramicVideoUrlResponse_
{
  typedef PanoramicVideoUrlResponse_<ContainerAllocator> Type;

  PanoramicVideoUrlResponse_()
    {
    }
  PanoramicVideoUrlResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PanoramicVideoUrlResponse_

typedef ::common::PanoramicVideoUrlResponse_<std::allocator<void> > PanoramicVideoUrlResponse;

typedef boost::shared_ptr< ::common::PanoramicVideoUrlResponse > PanoramicVideoUrlResponsePtr;
typedef boost::shared_ptr< ::common::PanoramicVideoUrlResponse const> PanoramicVideoUrlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::PanoramicVideoUrlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::common::PanoramicVideoUrlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/PanoramicVideoUrlResponse";
  }

  static const char* value(const ::common::PanoramicVideoUrlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
;
  }

  static const char* value(const ::common::PanoramicVideoUrlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PanoramicVideoUrlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::PanoramicVideoUrlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::common::PanoramicVideoUrlResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_PANORAMICVIDEOURLRESPONSE_H
