// Generated by gencpp from file common/PatrolControlResponse.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_PATROLCONTROLRESPONSE_H
#define COMMON_MESSAGE_PATROLCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common
{
template <class ContainerAllocator>
struct PatrolControlResponse_
{
  typedef PatrolControlResponse_<ContainerAllocator> Type;

  PatrolControlResponse_()
    : status_code(0)  {
    }
  PatrolControlResponse_(const ContainerAllocator& _alloc)
    : status_code(0)  {
  (void)_alloc;
    }



   typedef int32_t _status_code_type;
  _status_code_type status_code;





  typedef boost::shared_ptr< ::common::PatrolControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::PatrolControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PatrolControlResponse_

typedef ::common::PatrolControlResponse_<std::allocator<void> > PatrolControlResponse;

typedef boost::shared_ptr< ::common::PatrolControlResponse > PatrolControlResponsePtr;
typedef boost::shared_ptr< ::common::PatrolControlResponse const> PatrolControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::PatrolControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::PatrolControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::PatrolControlResponse_<ContainerAllocator1> & lhs, const ::common::PatrolControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status_code == rhs.status_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::PatrolControlResponse_<ContainerAllocator1> & lhs, const ::common::PatrolControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::PatrolControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::PatrolControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::PatrolControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::PatrolControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::PatrolControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::PatrolControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::PatrolControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7714e81371f09d2d15e163f37002ef48";
  }

  static const char* value(const ::common::PatrolControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7714e81371f09d2dULL;
  static const uint64_t static_value2 = 0x15e163f37002ef48ULL;
};

template<class ContainerAllocator>
struct DataType< ::common::PatrolControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/PatrolControlResponse";
  }

  static const char* value(const ::common::PatrolControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::PatrolControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status_code\n"
"#0失败，1完成\n"
"#2低电量充电中 无法执行任务\n"
"#3已有巡检任务执行中，无法执行任务\n"
"\n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::common::PatrolControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::PatrolControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PatrolControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::PatrolControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::PatrolControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "status_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_PATROLCONTROLRESPONSE_H
