// Generated by gencpp from file common/PIDRequest.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_PIDREQUEST_H
#define COMMON_MESSAGE_PIDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common
{
template <class ContainerAllocator>
struct PIDRequest_
{
  typedef PIDRequest_<ContainerAllocator> Type;

  PIDRequest_()
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)  {
    }
  PIDRequest_(const ContainerAllocator& _alloc)
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)  {
  (void)_alloc;
    }



   typedef float _kp_type;
  _kp_type kp;

   typedef float _ki_type;
  _ki_type ki;

   typedef float _kd_type;
  _kd_type kd;





  typedef boost::shared_ptr< ::common::PIDRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::PIDRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PIDRequest_

typedef ::common::PIDRequest_<std::allocator<void> > PIDRequest;

typedef boost::shared_ptr< ::common::PIDRequest > PIDRequestPtr;
typedef boost::shared_ptr< ::common::PIDRequest const> PIDRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::PIDRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::PIDRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::PIDRequest_<ContainerAllocator1> & lhs, const ::common::PIDRequest_<ContainerAllocator2> & rhs)
{
  return lhs.kp == rhs.kp &&
    lhs.ki == rhs.ki &&
    lhs.kd == rhs.kd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::PIDRequest_<ContainerAllocator1> & lhs, const ::common::PIDRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::PIDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::PIDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::PIDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::PIDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::PIDRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::PIDRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::PIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08d0ca1f582560895ecba909de1d88ec";
  }

  static const char* value(const ::common::PIDRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08d0ca1f58256089ULL;
  static const uint64_t static_value2 = 0x5ecba909de1d88ecULL;
};

template<class ContainerAllocator>
struct DataType< ::common::PIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/PIDRequest";
  }

  static const char* value(const ::common::PIDRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::PIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 kp\n"
"float32 ki\n"
"float32 kd\n"
;
  }

  static const char* value(const ::common::PIDRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::PIDRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.ki);
      stream.next(m.kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PIDRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::PIDRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::PIDRequest_<ContainerAllocator>& v)
  {
    s << indent << "kp: ";
    Printer<float>::stream(s, indent + "  ", v.kp);
    s << indent << "ki: ";
    Printer<float>::stream(s, indent + "  ", v.ki);
    s << indent << "kd: ";
    Printer<float>::stream(s, indent + "  ", v.kd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_PIDREQUEST_H
