// Generated by gencpp from file common/PositionControl.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_POSITIONCONTROL_H
#define COMMON_MESSAGE_POSITIONCONTROL_H

#include <ros/service_traits.h>


#include <common/PositionControlRequest.h>
#include <common/PositionControlResponse.h>


namespace common
{

struct PositionControl
{

typedef PositionControlRequest Request;
typedef PositionControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PositionControl
} // namespace common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common::PositionControl > {
  static const char* value()
  {
    return "a9519dff92fdaba9780b7a4c059be1f8";
  }

  static const char* value(const ::common::PositionControl&) { return value(); }
};

template<>
struct DataType< ::common::PositionControl > {
  static const char* value()
  {
    return "common/PositionControl";
  }

  static const char* value(const ::common::PositionControl&) { return value(); }
};


// service_traits::MD5Sum< ::common::PositionControlRequest> should match
// service_traits::MD5Sum< ::common::PositionControl >
template<>
struct MD5Sum< ::common::PositionControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common::PositionControl >::value();
  }
  static const char* value(const ::common::PositionControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::PositionControlRequest> should match
// service_traits::DataType< ::common::PositionControl >
template<>
struct DataType< ::common::PositionControlRequest>
{
  static const char* value()
  {
    return DataType< ::common::PositionControl >::value();
  }
  static const char* value(const ::common::PositionControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common::PositionControlResponse> should match
// service_traits::MD5Sum< ::common::PositionControl >
template<>
struct MD5Sum< ::common::PositionControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common::PositionControl >::value();
  }
  static const char* value(const ::common::PositionControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::PositionControlResponse> should match
// service_traits::DataType< ::common::PositionControl >
template<>
struct DataType< ::common::PositionControlResponse>
{
  static const char* value()
  {
    return DataType< ::common::PositionControl >::value();
  }
  static const char* value(const ::common::PositionControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MESSAGE_POSITIONCONTROL_H
