// Generated by gencpp from file common/StopControl.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_STOPCONTROL_H
#define COMMON_MESSAGE_STOPCONTROL_H

#include <ros/service_traits.h>


#include <common/StopControlRequest.h>
#include <common/StopControlResponse.h>


namespace common
{

struct StopControl
{

typedef StopControlRequest Request;
typedef StopControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopControl
} // namespace common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common::StopControl > {
  static const char* value()
  {
    return "13e671c4ccd3de8f6fad86254c69924f";
  }

  static const char* value(const ::common::StopControl&) { return value(); }
};

template<>
struct DataType< ::common::StopControl > {
  static const char* value()
  {
    return "common/StopControl";
  }

  static const char* value(const ::common::StopControl&) { return value(); }
};


// service_traits::MD5Sum< ::common::StopControlRequest> should match
// service_traits::MD5Sum< ::common::StopControl >
template<>
struct MD5Sum< ::common::StopControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common::StopControl >::value();
  }
  static const char* value(const ::common::StopControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::StopControlRequest> should match
// service_traits::DataType< ::common::StopControl >
template<>
struct DataType< ::common::StopControlRequest>
{
  static const char* value()
  {
    return DataType< ::common::StopControl >::value();
  }
  static const char* value(const ::common::StopControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common::StopControlResponse> should match
// service_traits::MD5Sum< ::common::StopControl >
template<>
struct MD5Sum< ::common::StopControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common::StopControl >::value();
  }
  static const char* value(const ::common::StopControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::StopControlResponse> should match
// service_traits::DataType< ::common::StopControl >
template<>
struct DataType< ::common::StopControlResponse>
{
  static const char* value()
  {
    return DataType< ::common::StopControl >::value();
  }
  static const char* value(const ::common::StopControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MESSAGE_STOPCONTROL_H
