// Generated by gencpp from file common/TakePictureRequest.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_TAKEPICTUREREQUEST_H
#define COMMON_MESSAGE_TAKEPICTUREREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common
{
template <class ContainerAllocator>
struct TakePictureRequest_
{
  typedef TakePictureRequest_<ContainerAllocator> Type;

  TakePictureRequest_()
    : take_picture()  {
    }
  TakePictureRequest_(const ContainerAllocator& _alloc)
    : take_picture(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _take_picture_type;
  _take_picture_type take_picture;





  typedef boost::shared_ptr< ::common::TakePictureRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::TakePictureRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TakePictureRequest_

typedef ::common::TakePictureRequest_<std::allocator<void> > TakePictureRequest;

typedef boost::shared_ptr< ::common::TakePictureRequest > TakePictureRequestPtr;
typedef boost::shared_ptr< ::common::TakePictureRequest const> TakePictureRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::TakePictureRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::TakePictureRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::TakePictureRequest_<ContainerAllocator1> & lhs, const ::common::TakePictureRequest_<ContainerAllocator2> & rhs)
{
  return lhs.take_picture == rhs.take_picture;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::TakePictureRequest_<ContainerAllocator1> & lhs, const ::common::TakePictureRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::TakePictureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::TakePictureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::TakePictureRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::TakePictureRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::TakePictureRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::TakePictureRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::TakePictureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abb202ce41f595a07dc3199477972edd";
  }

  static const char* value(const ::common::TakePictureRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabb202ce41f595a0ULL;
  static const uint64_t static_value2 = 0x7dc3199477972eddULL;
};

template<class ContainerAllocator>
struct DataType< ::common::TakePictureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/TakePictureRequest";
  }

  static const char* value(const ::common::TakePictureRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::TakePictureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string take_picture\n"
;
  }

  static const char* value(const ::common::TakePictureRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::TakePictureRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.take_picture);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TakePictureRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::TakePictureRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::TakePictureRequest_<ContainerAllocator>& v)
  {
    s << indent << "take_picture: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.take_picture);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_TAKEPICTUREREQUEST_H
