// Generated by gencpp from file common/TakePicture.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_TAKEPICTURE_H
#define COMMON_MESSAGE_TAKEPICTURE_H

#include <ros/service_traits.h>


#include <common/TakePictureRequest.h>
#include <common/TakePictureResponse.h>


namespace common
{

struct TakePicture
{

typedef TakePictureRequest Request;
typedef TakePictureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakePicture
} // namespace common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common::TakePicture > {
  static const char* value()
  {
    return "5810510cbe479584b13b0db4c9da21a6";
  }

  static const char* value(const ::common::TakePicture&) { return value(); }
};

template<>
struct DataType< ::common::TakePicture > {
  static const char* value()
  {
    return "common/TakePicture";
  }

  static const char* value(const ::common::TakePicture&) { return value(); }
};


// service_traits::MD5Sum< ::common::TakePictureRequest> should match
// service_traits::MD5Sum< ::common::TakePicture >
template<>
struct MD5Sum< ::common::TakePictureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common::TakePicture >::value();
  }
  static const char* value(const ::common::TakePictureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::TakePictureRequest> should match
// service_traits::DataType< ::common::TakePicture >
template<>
struct DataType< ::common::TakePictureRequest>
{
  static const char* value()
  {
    return DataType< ::common::TakePicture >::value();
  }
  static const char* value(const ::common::TakePictureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common::TakePictureResponse> should match
// service_traits::MD5Sum< ::common::TakePicture >
template<>
struct MD5Sum< ::common::TakePictureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common::TakePicture >::value();
  }
  static const char* value(const ::common::TakePictureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common::TakePictureResponse> should match
// service_traits::DataType< ::common::TakePicture >
template<>
struct DataType< ::common::TakePictureResponse>
{
  static const char* value()
  {
    return DataType< ::common::TakePicture >::value();
  }
  static const char* value(const ::common::TakePictureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MESSAGE_TAKEPICTURE_H
