@startuml
User -> Server : Create Websocket
Server -> User : Websocket Created
alt HeartBeat Detect
    User -> Server : Send Ping
    Server -> User : Send Pong

end
ROS -> Server : Publish ROS Topic
Server -> ROS : Subscribe ROS Topic
Server -> User : Forward ROS Topic
User -> User : Preview ROS Topic


@enduml