@startuml 
title Task Create Sequence Diagram
User -> Server : Create Tasks
Server -> Server : Check if the task is valid
Server -> Server : Create the XML file
Server -> ROS : Call corresponding ROS service
ROS -> ROS : Execute the task 
ROS -> Server : Return the result
database "mysql" as mysql
Server -> mysql : Store the result
mysql -> Server : Return the result
Server -> User : Return the result
@enduml
